- name: variables
  hosts: localhost
  vars:  #Pllaylevel variables
    COURSE: "Devops"
    TRAINER: "SHIVA"
    DURATION: "120HRS"
  tasks: 
    -name: print override information
     vars: #Tasklevel variables
      COURSE: "Terrafrom"
    ansible.builtin.debug:
      msg: "I am learing {{COURSE}} from {{TRAINER}} duration of {{DURATION}}"
    -name: print playlevel
     ansible.builtin.debug:
      msg: "I am learing {{COURSE}} from {{TRAINER}} duration of {{DURATION}}"
    
    