- name: files
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:  
    - name: variables from files
      ansible.builtin.debug:
        msg : "Hi, Iam learning {{COURSE}} from {{TRAINER}} of duration {{DURATION}}"


